[build]
  command = "npm run production"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404

  [[headers]]
    for = "/fonts/*"
      [headers.values]
      Cache-Control = "public, max-age=31536000"